title: mxawng
subtitle: no longer solarized!
author: Max Wang
url: https://mxawng.com
image: /img/cover.png

source: src
exclude: [ts]

collections_dir: collections
collections:
  externals: ~
  code:
    sort_by: order

sass:
  implementation: sass-embedded
  sass_dir: ./css

scripts: [main, rhythm]
styles: [site]

nav:
  - name: about
    url: /about/
    submenu:
      - name: contact
        url: /contact/
      - name: this site
        url: /about/site/
  - name: writing
    url: /writing/
    submenu:
      - name: poetry
        url: /writing/poetry/
  - name: stuff
    url: /stuff/
    submenu:
      - name: code
        url: /stuff/code/
      - name: music
        url: /stuff/music/
      - name: dance
        url: /stuff/dance/
  - name: things
    url: /things/
    submenu:
      - name: opinions
        url: /things/opinions/
      - name: unthings
        url: /things/unthings/

excerpt_separator: "<!--more-->"
