title: mxawng
subtitle: no longer solarized!
author: Max Wang
url: https://mxawng.com
url_old: http://www.mxawng.com
image: /img/cover.png

source: src
exclude: [ts]

# during development, run:
#
# jekyll serve --config _config.yml,_config_dev.yml
dev: false

#-------------------------------------------------
# static resources
#
# static_version adds a version number to all static resource files.
# bumping it forces clients to bypass cache.  see the rewrite rule
# in mxawng.nginx.

static_version: 3

sass:
  implementation: sass-embedded
  sass_dir: ./css

scripts: [rhythm]
styles: [site]

#-------------------------------------------------
# posts & collections

collections_dir: collections
collections:
  externals: ~
  code:
    sort_by: order
  recs: ~

excerpt_separator: "<!--more-->"

#-------------------------------------------------
# site content

nav:
  - name: about
    url: /about/
    submenu:
      - name: contact
        url: /contact/
      - name: this site
        url: /about/site/
  - name: writing
    url: /writing/
    submenu:
      - name: poetry
        url: /writing/poetry/
  - name: stuff
    url: /stuff/
    submenu:
      - name: code
        url: /stuff/code/
      - name: music
        url: /stuff/music/
      - name: dance
        url: /stuff/dance/
  - name: things
    url: /things/
    submenu:
      - name: wireeater
        url: /things/wireeater/
      - name: unthings
        url: /things/unthings/
