title: mxawng
subtitle: no longer solarized!
author: Max Wang
url: https://mxawng.com
url_old: http://www.mxawng.com
image: /img/cover.png

source: src
exclude: [ts]

#-------------------------------------------------
# static resources
#
# static_version adds a version number to all static resource files.
# bumping it forces clients to bypass cache.  see the rewrite rule
# in mxawng.nginx.

static_version: 26

sass:
  implementation: sass-embedded
  sass_dir: ./css

scripts: [rhythm]
styles: [site]

root_dir: _root   # for favicons, etc.; @see: _plugins/copy-root.rb

#-------------------------------------------------
# posts & collections

collections_dir: collections
collections:
  externals: ~
  poems:
    sort_by: order
  code:
    sort_by: order
  recs:
    categories:
      - name: brain
        display: headspace
        tags: [words, music, watch, products]
      - name: bos
        display: college town
        tags: [food]
      - name: nyc
        display: favorite city
        tags: [food]
      - name: la
        display: wasteland of cars
        tags: [food]
    tags:
      - name: food
        display: put in my mouth
      - name: words
        display: consume textually
      - name: music
        display: stick in my ears
      - name: watch
        display: put in my eyeballs
      - name: products
        display: spend money on
#      - name: clothes
#        display: cover my body with
#      - name: software
#        display: stuff inside my laptop
    sort_by: rank
  sale:
    sort_by: price

excerpt_separator: "<!--more-->"

#-------------------------------------------------
# site content

nav:
  - name: about
    url: /about/
    submenu:
      - name: contact
        url: /contact/
      - name: this site
        url: /about/site/
  - name: writing
    url: /writing/
    submenu:
      - name: poetry
        url: /writing/poetry/
  - name: stuff
    url: /stuff/
    submenu:
      - name: code
        url: /stuff/code/
      - name: music
        url: /stuff/music/
      - name: dance
        url: /stuff/dance/
  - name: things
    url: /things/
    submenu:
      - name: wireeater
        url: /things/wireeater/
      - name: unthings
        url: /things/unthings/
